on: push

jobs:
    npm-build:
        name: nmp build工作
        runs-on: ubuntu-latest
        steps:
            - name: 读取仓库代码
            uses: actions/checkout@v4

            - name: npm install
            run: npm install

            - name: 构建
            run: npm run build
